server.port=8082
spring.application.name=user-service
spring.data.mongodb.uri=mongodb+srv://root:root@auth-cluster.cutqnwn.mongodb.net/?appName=auth-cluster
spring.data.mongodb.database=auth
spring.data.redis.host=redis-10765.c326.us-east-1-3.ec2.cloud.redislabs.com
spring.data.redis.password=UvDiVyIgyONqZJ7Mk6MQbySKZKiqUa95
spring.data.redis.port=10765